### ISSUE TITLE
Clicking a modal overlay should not close modal

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-web#437]
From the ARIA design practices spec:

> Even if the user clicks outside of the dialog on the application which invoked the dialog, focus remains in the dialog.
> http://www.w3.org/TR/wai-aria-practices/#dialog_modal

**Comment by skitterm** [comment]
I feel stuck in the modal if I have to click a small "X" button instead of just clicking outside the modal anywhere to close. Bootstrap 4's modals allow clicking anywhere outside the modal to close, as do modals on esri.com.

Is there a way to satisfy accessibility needs while still allowing clicking outside the modal to close?

**Comment by paulcpederson** [comment]
Reading through the spec I see this has maybe changed since this issue was closed:

> in some implementations, attempts to interact with the inert content cause the dialog to close.

Looks like the door is open to possibly close on click outside the modal now. @patrickarlt thoughts?
