### ISSUE TITLE
Accordions

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-web#452]
@nikolaswise @paulcpederson @asangma @chrisferenci @driskull @CassidyB @stieman 

**Accordion +/-  versus  v/^**

There's a considerable concern with our pattern using +/- for accordions.

In complex dialogues where you can add, create, delete, zoom, or unzoom... the +/- icons can serve as confusing.

Suggest using the icons below for accordions to limit this confusion: 
![carrots](https://cloud.githubusercontent.com/assets/14083530/11695636/1ea15bb8-9e65-11e5-87bc-cb3c12671e1e.png)

**Comment by asangma** [comment]
@patrickarlt Thanks for the suggestion!
So a case which *might* require a caret on the right side would look something like this:
![arcgis-popup-accordion-design-avs-2](https://cloud.githubusercontent.com/assets/12503298/12922837/f9cbf446-cf07-11e5-8f38-0c5bf771bf74.jpg)

I had found it a bit weird to point left like this, but I think if we were consistent with the ```points toward title``` for closed pattern for accordions, it could work.

I am using this example because we also have the collapse/expand caret for the entire map popup which could be seen to have some overlap with the accordion carets.  I don't see it as an issue.  @HeathMeyette?

**Comment by asangma** [comment]
@bstifle Thoughts?

**Comment by asangma** [comment]
@chrisferenci Thought?

**Comment by bstifle** [comment]
@asangma @paulcpederson Leaning for what Paul is saying. The arrow pointing left feels wrong.

**Comment by asangma** [comment]
@bstifle Truth is, the right side, left pointing caret would hopefully be an edge case.  And the ```points toward title``` rule would be a clean and easy-to-follow rule. Ya?

**Comment by bstifle** [comment]
@asangma 
You have thoroughly convinced me. Zing!

**Comment by HeathMeyette** [comment]
@asangma It looks like we are coming to agreement on this. I am most partial to the > / V as this seems most normal to me. 

Although it’s really not ideal, it seems as long as the arrow points inward (towards it’s title/label) it should be understandable. We should still work towards keeping the arrows on the left as much as possible but pointing inwards helps to not setup the expectation of swipe direction.

**Comment by nikolaswise** [comment]
Last call for opposition @fgarofalo10 & @CassidyB

**Comment by fgarofalo10** [comment]
in https://esri.box.com/ArcGIS-Pro-design-guide on page 21 and 22, describes "Expanders" which from the Desktop/Pro realm is the similar to Accordions. pg 44-45 is tree view. there seems to be some related ideas in this discussion thread. 

cc-ing @kyle-03674 @richc117 @HeathMeyette @asangma

**Comment by nikolaswise** [comment]
> Sounds good, please proceed.
- @fgarofalo10 

This is addressed in #477.

**Comment by asangma** [comment]
![giphy-5](https://cloud.githubusercontent.com/assets/12503298/13016126/d4cb66e2-d171-11e5-8001-c1ce30fb730c.gif)
