### ISSUE TITLE
App Switcher

### ISSUE THREAD

**Issue by mpalmeresri** [Esri/calcite-web#534]
Hey Nik,

Here's a quick sketch of the app switcher in a med-fi wireframe we are considering navigation for esri.com.

It's not revolutionary, but hopefully this gives you an idea of placement for desktop.

We are still questioning the use on tablet or mobile as we don't see too many use cases that would support the effort.

Talk soon,

Matt
![app switcher](https://cloud.githubusercontent.com/assets/16671099/14357833/2425e07a-fc9f-11e5-94a0-8788d3eaa1d7.png)

**Comment by nikolaswise** [comment]
@mpalmeresri :+1: Any wires of what that 'view all' button does?

**Comment by mpalmeresri** [comment]
Not yet. Haven't identified the number of apps that might appear here yet. I'm, open to either a expansion of more icons in the pop-over or sending them to the Apps Gateway for more control in filter/sort.

________________________________

**Comment by nikolaswise** [comment]
#538 

Rounds of iteration and design feedback will happen in new issues.

**Comment by fgarofalo10** [comment]
Jorge G. is already in the process of creating an icon for the top header to toggle the AppSwitcher open and closed, which will be added to the Calcite set once finalized.

here is a concept that has been discussed:
![appswitcher_concept](https://cloud.githubusercontent.com/assets/3503751/14467808/d4de0460-0091-11e6-9a99-09d437ef691f.jpg)

Note - in the lower left corner sketch, the Icon displayed in each "app" option would be visually a watermark, if an product icon exists for that given "app" otherwise text of the "app" name/title would only be displayed.

In conversations with Sentha & Jeremy, they are interested in having a dojo widget created for the entire top header ...since seemed to be related to some of the hurdles Paul came across when trying to update the CSS for the top header across the "home app," 3D Scene Viewer, Presentation app, Organization Dashboard, etc. This new top header widget would include the new concepts of the AppSwitcher and the User Account Switcher.

cc-ed @asangma @HeathMeyette @snelsonux

**Comment by CassidyB** [comment]
@nikolaswise The view all button is mean to bring up an overlay window.  Palmer and I will work on this a bit more.

**Comment by snelsonux** [comment]
have we discussed the following yet?

1. up-front usability/accessibility concerns that need addressing 
- having users make the distinction between web-based apps of the platform and non-web-based apps (that aren’t in the switcher)
- making the distinction between apps they have permission to access and no permission to access

**Comment by nikolaswise** [comment]
@fgarofalo10 Step one is to define the basic markup, ui, and styles canonically in the framework. Step 2 is to create a custom element and a dojo widget that be easily consumed in other projects. This is will it's own repo.

@CassidyB Yeah, the Big Modal. When we have wires for this, open a new issue and put em in there.

@snelsonux These are excellent questions that will get explored in future issues. We need to start at the basics though - what apps are in here, what are their icons.

**Comment by snelsonux** [comment]
@nikolaswise thanks for responding. I don't know, I feel like what I am asking about is a bit more primordial than what we've seen in the wires/sketches. In other words, answering the question "what apps are in here" requires us to make a **decision ** between apps that are in here and apps that aren't in here. Our decision will require users to make an appropriate **distinction** so that they understand the scope of the switcher and that other apps are still discoverable. Thoughts?

**Comment by snelsonux** [comment]
perhaps the above needs to be a conversation between me and @fgarofalo10 / @mpalmeresri

**Comment by fgarofalo10** [comment]
the "apps" displayed need for follow the access privileges of the SHARE / Permissions API from ArcGIS Online.

In this line of thinking, if a person has access to: A) ArcGIS Online [http://www.arcgis.com/home/content.html], B) Storymaps [storymaps.arcgis.com/en/my-stories/], D) ArcGIS for Developers [https://developers.arcgis.com/applications/#/], E) Operations Dashboard, F) Collector
Then perhaps for the non-web-based apps, the app switcher needs to go to the ArcGIS Online Item Details page for the app, which from there the person can launch the native app.

**Comment by snelsonux** [comment]
I like it, @fgarofalo10

**Comment by nikolaswise** [comment]
@snelsonux @fgarofalo10 Indeed. The API for populating this pattern still needs to be defined. This business logic will get written and structured in the componenet/widget repo. At the framework level, we're exclusively interested in styling, markup structure, and basic interactivity. 

I would suggest someone with the properly privileges create the repo `esri/calcite-app-switcher` to get this started.

**Comment by CassidyB** [comment]
@nikolaswise Good Idea, I will take that on.

**Comment by HeathMeyette** [comment]
Just FYI: From a past conversation with @sentha-sivabalan and @jbartley the initial apps to include were designated as 

	- Operations Dashboard
	- Workforce 
	- Survey 123
	- Business Analyst Online (purchased)
	- Community Analyst (purchased)
	- Geo Planner
	- Story Maps
	- Open Data
	- AppStudio
	- Marketplace Apps (weren't sure how these fit in) (purchased)

**Comment by snelsonux** [comment]
thanks @HeathMeyette this is important to keep in front of...lots of apps there about half of them have their own launcher icons. When this gets to visual design, we will need to make sure that there isn't an odd hierarchy imposed by some having icons and some not having icons.
