### ISSUE TITLE
Tooltip being clipped when the element is contained in a overflow:hidden container

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-web#666]
With the current tooltip implementation, Tooltip will be in the same container as the element.
If the container has `overflow: hidden;`, the tooltips will be clipped.
Tooltips should be added to the body with an absolute position.

**Comment by paulcpederson** [comment]
so use javascript for the tooltips?

**Comment by ffaubry** [comment]
@paulcpederson Are you suggesting that the tooltip included in CW is what it is and if we need more flexible/powerful tooltip then we should use third party js solution?
I'm fine with this, but I would then suggest to update the doc to be sure it is an understood limitation of the tooltip in CW.

**Comment by paulcpederson** [comment]
No, nothing like that. Apologies for being terse. I'm honestly asking if you think that would be a better approach. I'm fine either way. 

I do, however, think our current solution is pretty eloquent. for 90% of use cases it's going to work fine. 

Did you try wrapping your element with `overflow: hidden

**Comment by nikolaswise** [comment]
@ffaubry Ideally, we try to keep components as simple and JS-free as possible. 

Can you provide your markup structures so we can address the problem your having? 

Ideally, issues should provide information about the problem at hand, and how calcite web is not meeting your needs rather than a flat declaration of how things *should* be.

**Comment by ffaubry** [comment]
@nikolaswise Thanks for clarifying the strategy of the calcite web regarding patterns and components and js code.
In the dashboard project, we decided to only use calcite web for the styles (great job there!) and we are staying away from the buggy calcite js code. We have re-implemented all components and patterns as Ember js components.
I changed the title of this issue to match your requirements. 
I don't need this issue to be addressed anymore.

**Comment by nikolaswise** [comment]
@ffaubry Im sorry you felt the need to reimplement behavior rather than opening issues – your bug reporting on the JS could have helped move everyone forward. 

We appreciate bug reporting, but this behavior is not conducive to the health of the framework project. Rather than getting frustrated with us (these aren't arbitrary "requirements"), let us know how we can help you and your team – thats what we're here for.
