### ISSUE TITLE
Top Nav discrepancy between proto.esri.com & what is in Calcite examples

### ISSUE THREAD

**Issue by eleanorh** [Esri/calcite-web#688]
@CassidyB @paulcpederson @nikolaswise  - What is the recommended Global/Top nav pattern?

The one I see on [proto.esri.com](http://proto.esri.com/#/detail/Navigation/Global%20Navigation/1) has hover/active state indicated by a blue line under the text. 
![image](https://cloud.githubusercontent.com/assets/3044334/19286582/0c49da22-8fb3-11e6-8679-1b8f852e1b9e.png)

The one in the Calcite examples & documentation has hover/active state indicated by a blue line above the text.

![image](https://cloud.githubusercontent.com/assets/3044334/19322827/77f97dec-906f-11e6-8121-b7d3bc6b3aaa.png)

Which one is correct?

For my reference, this issue logged to help us make good decision in https://github.com/ArcGIS/arcgis-doc-website/issues/4121 and moving forward in other implementations.

**Comment by nikolaswise** [comment]
@eleanorh the current agreement is on the bar below the text.

Calcite Web hasn't made this transition yet due to generalized Top Nav Uncertainty, which is currently in the process of being resolved.

The best course of action is to style as little as possible, and rely on the framework as much as possible. This way, when we move to a final release of Calcite Web you will get all the latest styles and patterns automatically.

**Comment by eleanorh** [comment]
Thanks @nikolaswise
