### ISSUE TITLE
calcite-web.js error

### ISSUE THREAD

**Issue by ajbroadbent** [Esri/calcite-web#700]
On pages with nested TOCs, the "Back to Top" link isn't showing up.  I'm seeing an error in calcite-web.js on those pages.  For example, on http://docdev.arcgis.com/en/arcgis-online/create-maps/change-style.htm, the link does not appear if you scroll down, but on http://docdev.arcgis.com/en/arcgis-online/create-maps/add-layers.htm, it does.

**Comment by ajbroadbent** [comment]
This site is on v1.0.0-beta.33

**Comment by paulcpederson** [comment]
@ajbroadbent the animation on that page for the accordion isn't the same as Calcite Web, leading me to believe there is some other JS running on the page to do the open/close of the accordion? 

There are also several links on that page that aren't grouped properly for an accordion. The first two and last two links aren't inside of an accordion section, which may break them?

If there is actually a separate script that is setting the height, I recommend just removing the `js-accordion` class from the accordion so that `calcite-web.js` just ignores it. Does that make sense?

**Comment by ajbroadbent** [comment]
Yup.  I'll try that.  I'll also check any other scripts running.  I thought calcite-web because it's issuing an error on that page and not the other one.

**Comment by paulcpederson** [comment]
For more context, here is what I think might be happening:  on `init` `calcite-web.js` is finding everything with a class of `js-accordion` and then attaching events to all of the headers of those sections. 

It then tries to set the `role` attribute on a DOM node that is presumably missing (do to missing accordion headers?), and this causes the script to crash. At this point all `calcite-web` scripts will stop working. So it *is* a Calcite Web thing, but I think it could be fixed by either changing your side menu to include headers and accordion sections for each section, or by just removing the `js-accordion` class. 

Looking at other pages on this site it seems like they work because all of the accordion sections have headers, so it is probably that.

**Comment by ajbroadbent** [comment]
Cool, thank you.  That gives me a good starting point.

**Comment by paulcpederson** [comment]
@ajbroadbent how is it going? Did you manage to fix this? If so, do you mind if I close the issue?

**Comment by ajbroadbent** [comment]
You can go ahead and close it.  Thanks!
