### ISSUE TITLE
grid margins badly aligned in responsive design

### ISSUE THREAD

**Issue by GreavesEsri** [Esri/calcite-web#717]
Consider this grid setup:

```
<div class="grid-container">
  	<div class="column-24 tablet-column-12 phone-column-6" style="
    background-color: #ccc;
">
      <div style="background-color: #eee;height:50px;text-align: center;vertical-align:middle;padding-top:20px;">ALWAYS VISIBLE</div>
  </div>
      <div class="column-24 tablet-column-12 phone-column-6">
        <div class="phone-hide column-6 tablet-column-6" style="/* height: 200px; */background-color: #cccccc;">
          <div style="background-color:#fff; height:200px; text-align: center; vertical-align:middle; padding-top:100px;">HIDE ON PHONE
  </div>
        </div>
        <div class="column-18 tablet-column-6 phone-column-6" style="/* height: 200px; */background-color: #cccccc;">
  			<div style="background-color:#fff; height:200px; text-align: center; vertical-align:middle; padding-top:100px;">ALWAYS VISIBLE</div>
  		</div>
      </div>
  </div>
```

Which renders like this on desktop:
![image](https://cloud.githubusercontent.com/assets/24479249/21055100/fc895fb2-bde4-11e6-963a-588ce4788426.png)

but like this on phone:
![image](https://cloud.githubusercontent.com/assets/24479249/21055651/3656cc32-bde7-11e6-9a60-761624e53677.png)

This seems to be caused by the css rule:
```
[class*="column-"] [class*="column-"]:first-of-type {
    margin-left: -0.5rem;
}
```

which still recognizes the div element which .phone-hide is applied to (using display:none) as ':first-of-type' even though it is not visible or taking up space. This also happens where you want to remove the right-most element via .phone-hide, etc., due to :last-of-type.

Is there a better way to do this?

Thanks!

**Comment by paulcpederson** [comment]
@GreavesEsri you can add the class `phone-first-column` to the mis-aligned column to fix it. 

We try to detect based on the markup when the column is the first in the row, but sometimes (as in this case) you'll have to use the `X-first-column` classes manually.

As a side note, if you're interested in saving a few bites you can use `column-24` instead of `column-24 tablet-column-12 phone-column-6`. A `column-24` is automatically converted into a `tablet-column-12` and a `phone-column-6` so writing it is optional.
