### ISSUE TITLE
Allow JavaScript methods to be called on individual elements

### ISSUE THREAD

**Issue by ssylvia** [Esri/calcite-web#735]
We're leveraging this framework in a single page react app and need to initialize and destroy different components at different times. Would like to do something like the following:

```js
...
componentDidMount() {
  this.myDrawer = drawer({
    node: this.drawerToggle
  });
}

componentWillUnmount() {
   this.myDrawer.destroy();
}

handleClick() {
  this.myDrawer.toggle();
}

render() {
  return (
    <div>
      <button type="button" onClick={this.handleClick} />
      <div type="button" ref={(ref) => {this.drawer = ref}}>
         ...
      </div>
    </div>
  );
}
...
```

**Comment by paulcpederson** [comment]
OK, let me make sure I get this. Essentially you'd like to pass the drawer function a dom node and then it would scope binding events to just that node? And then `drawer()` to return an object with multiple methods (`toggle()`, `destroy()`) for managing that drawer.

I think that makes sense as an API, and I really like it, but it is definitely very different from how it is now. I'm super open to it, but it would be basically a complete rewrite. 

That being said, it could definitely be worth it because an API like this would make it consumable by other frameworks like angular, ember, etc as well, right?

@patrickarlt would an API like this help you do angular directives/web components as well?

**Comment by paulcpederson** [comment]
Also, @dbouwman interested if this API would work from an Ember perspective?

For reference I think this is the API being discussed:

```
import drawer from 'calcite-web';

var node = document.querySelector('.js-my-drawer'); // or any dom node reference
var myDrawer = drawer({node: node});
// => { toggle: function () {}, destroy: function () {} }
```

**Comment by dbouwman** [comment]
@paulcpederson that api would be fine - we will have to wrap it into emberness, but that's pretty easy.

Other "asks" around this would be:
- keep the sass for the component isolated so that it can be pulled into a project that uses calcite-bootstrap
- option to specify side to dock to 
- option to specifying the width in px (we are using a drawer that is % based and it's "meh")

**Comment by ssylvia** [comment]
@paulcpederson Yep, the current JS works well when all the html is prebaked and you just have to call the initialize method when the page loads. However, it tends to break down when used in a single page app with dynamic rendering. Having an API like that to support adding a removing components one-at-time would be great.

**Comment by paulcpederson** [comment]
@dbouwman thanks for being my resident ember expert

**Comment by patrickarlt** [comment]
@paulcpederson this would certainly help Integrate into Angular as well. I still think that a web components based approach for the components will (eventually) be the best approach and will also  solve some of the CSS issues that @dbouwman mentions.

**Comment by macandcheese** [comment]
The Calcite Web project is deprecated and this will not be pursued.
