### ISSUE TITLE
Grid questions

### ISSUE THREAD

**Issue by jonathantneal** [Esri/calcite-web#754]
Hey there, I’m trying to understand some of the goals and motivations behind the Calcite grid system.

##### Would you explain the grid container width?

In [documentation/grid/#configuration](http://esri.github.io/calcite-web/documentation/grid/#configuration), we learn that `$container-width` is `95vw`, but in [base/_config.scss](https://github.com/Esri/calcite-web/blob/master/lib/sass/calcite-web/base/_config.scss#L35), we learn that `$container-width` is `1450px`. Did something change, or is one of them out of sync?

##### Would you explain the grid gutter?

In [type/_styles.scss_](https://github.com/Esri/calcite-web/blob/master/lib/sass/calcite-web/type/_styles.scss#L7-L9), we learn that the root `font-size` is `17px`. In [base/_config.scss](https://github.com/Esri/calcite-web/blob/master/lib/sass/calcite-web/base/_config.scss#L37), we learn that the `$column-gutter` is `1rem`. If both files are loaded, this would mean `1rem` is `17px`. Why is this relative to the size of the font? Should the width of the columns then also be relative? Also, the [$column-gutter-fallback](https://github.com/Esri/calcite-web/blob/master/lib/sass/calcite-web/base/_config.scss#L37) is `20px`, should it be 17px? How should designers (in Photoshop / Sketch) account for the grid (for instance, the outermost columns each include a half-gutter `8.5px`)?

RELATED: Looking at a Photoshop example for an upcoming project, I see a more normal whole-number pattern there. I see `16px` (`1rem`) gutters with `44px` (`2.75rem`) columns, and a desktop container width of `1440px` (`90rem`). Albeit, this means these comps will not line up with the web result.

##### Would you explain the grid pixel / viewport relationship?

> 1. Column widths are defined by the viewport size rather than percentage of their containers.

It looks like column widths are defined by pixel size, with a maximum size determined by the viewport. Should this text be updated? Or am I missing a grander idea?

> 2. Built-in smart defaults for responsive sizing puts less columns across the screen at smaller sizes, rather than smaller columns.

This results in some curious calculations right now, like `width: 1450px` when `@media (max-width: 859px)`.

```css
.column-12 {
  width: 725px;
  max-width: 47.5vw;
}

@media screen and (max-width: 859px) {
  .column-12 {
    width: 1450px;
    max-width: 95vw;
  }
}
```

Would you walk me through the scenario where these responsive queries make sense? Or is this an artifact of unoptimized Sass?

**Comment by paulcpederson** [comment]
1. `container-width` doc is out of date
2. gutter is relative to type as it is a convenient spacing unit. Consider the following excerpt of the brand guidelines documentation: ![screen shot 2017-01-03 at 12 51 08 pm](https://cloud.githubusercontent.com/assets/1031758/21622623/57719322-d1b3-11e6-93e0-3ffdd61feff5.png)
It's a similar idea. Using type units to space around type. I agree the base size of 17px leads to uncomfortable half-pixel measurements. Photoshop designers can make the outside spacing 9px.
3. Columns widths *are* determined by viewport size. The pixel width represents the largest possible size. I believe the reason it's written this way is that it will work in browsers that don't support viewport units because they will default to a static pixel width? Unsure.
4. That is an artifact of unoptimized Sass. I haven't had time to go through with a fine toothed comb and make sure the grid's Sass generates the perfect CSS. I would *love* help with that.

Hope that helps?

**Comment by asangma** [comment]
@TheBlueDog re: our conversation earlier today re: CW's grid and stuff.

**Comment by paulcpederson** [comment]
closing this, feel free to reopen this if questions remain unanswered, or open new issues with actionable bugs or feature requests.

**Comment by jonathantneal** [comment]
Has container-width doc been updated?

**Comment by paulcpederson** [comment]
@jonathantneal no thanks for the reminder

**Comment by paulcpederson** [comment]
Doc updated.
