### ISSUE TITLE
Scrolling on Modal box scrolling parent window as well

### ISSUE THREAD

**Issue by sanjibpanda** [Esri/calcite-web#766]
If modal box is opened and you scroll on top of it the parent window also getting scrolled.

Also, folks are wondering whether we should close the modal box when user clicks anywhere outside of modal box?

**Comment by paulcpederson** [comment]
I will look at the scrolling. 

Clicking outside to close was talked about a while back. Several people were concerned that their intense workflows that happen inside modals would be lost accidentally by clicking outside the dialog so that's why we require an explicit click of the close button to close it. Does that make sense?

**Comment by sanjibpanda** [comment]
Thanks @paulcpederson! Makes sense to me. I will pass the info to team.

**Comment by sanjibpanda** [comment]
@paulcpederson - Also, modal box is not opening on IE. Wondering whether its a known issue.

**Comment by mharrower** [comment]
Thanks for the explanation @paulcpederson - makes sense. 

Very minor priority, but mostly curious: do we have any way setup something like the Calcite modal with "close_on_click_outside = TRUE / FALSE" so that our modal could be configured to close on click-outside? Ours is a vanilla, passive FAQ that folks try to dismiss by clicking outside when they're read it (versus a panel with an OK button)

**Comment by paulcpederson** [comment]
you could maybe home roll this feature by using events on the calcite-web event bus. The pseudo code would be:

```
calcite.bus.on('modal:open', attachClickEvent);

function attachClickEvent (e) {
  document.querySelector('.js-modal-overlay.is-active').addEventListener('click', function (e) {
    calcite.bus.emit('modal:close')
  })
}
``` 

Probably would need to detach this and maybe check for click target being inside the modal content as well. Not sure if this helps.

We could possibly add an options object to `calcite.modal` like `calcite.modal({clickToClose: true})`?

**Comment by mharrower** [comment]
Sweet! Thanks Paul!

**Comment by paulcpederson** [comment]
Putting screenshot from #822 here as it's a good visual description of the bug:

![modal-window](https://user-images.githubusercontent.com/8091967/27544020-32faa22e-5a8c-11e7-92ff-c89bca568cb7.gif)

**Comment by skitterm** [comment]
This is fixed on desktop, but on iPad I'm still seeing the page scroll when dragging my finger over a modal.
