### ISSUE TITLE
how to: display content at the baseline of a card

### ISSUE THREAD

**Issue by jgravois** [Esri/calcite-web#792]
hello!

i have a question that is _0% likely_ to be a bug in calcite-web and _100% likely_ to be evidence that i do not understand the fundamentals of css.

how does one go about laying out specific content along the bottom of a card?

jsbin: http://jsbin.com/kopuzud/1/edit?html,output

```html
<div class="block-group block-group-4-up">
    <div class="card block">
        <div class="card-content card-bar-red">
        <h4 class="">enough to take up several lines</h4>
        <p class="font-size--1">bottom placement?</p>
        </div>
    </div>
    <div class="card block card-bar-green">
        <div class="card-content">
        <h4>less text</h4>
        <p class="font-size--1">bottom placement?</p>
        </div>
    </div>
</div>
```

**i tried**:
`leader`, `footer`, the generic css `margin-top` and even using flexbox `align-items` to no avail.

**Comment by paulcpederson** [comment]
http://jsbin.com/dufewujewa/1/edit?html,output

What you're looking for is the calcite-web class `card-last` which should be placed on the penultimate item. Essentially, any element after the element with `card-last` will be aligned with the bottom of the card. The class just adds `margin-bottom: auto` which works magically in flex-box.

```
<div class="block-group block-group-4-up">
  <div class="card block">
      <div class="card-content card-bar-red">
      <h4 class="card-last">enough to take up several lines</h4>
      <p class="font-size--1 trailer-0 leader-half">bottom placement?</p>
    </div>
  </div>
  <div class="card block card-bar-green">
      <div class="card-content">
      <h4 class="card-last">less text</h4>
      <p class="font-size--1 trailer-0 leader-half">bottom placement?</p>
    </div>
  </div>
</div>
```

In this example I've also added a bit of space above the paragraph, and cleared the margin below it with `trailer-0 leader-half` because I think this makes it look good. The space around the `p` is up to you, though. Follow your heart ❤️ ✨

**Comment by jgravois** [comment]
arghh.... the doc site already even had an example of it in use!

thanks magic man. i appreciate your patience.
![magic-man](https://pbs.twimg.com/profile_images/564271687437283328/Ias5gTV4.png)

**Comment by paulcpederson** [comment]
![giphy](https://cloud.githubusercontent.com/assets/1031758/24126042/13f9d75a-0d89-11e7-93a0-35329597b3b4.gif)

**Comment by asangma** [comment]
I just wanted to appreciate the use of Adventure Time here.
