### ISSUE TITLE
Possible need for unsets

### ISSUE THREAD

**Issue by jonathantneal** [Esri/calcite-web#820]
When building new components, I might unexpectedly inherit a Calcite style I don’t immediately discover. Usually an extra margin on list elements or an underlines on links.

Would you have any guidance on when to overset or unset Calcite styles? Could there be something like an unset **mixin** to protect elements from accidental styles now or in the future?

As a possible aside, should hover not be such a global default? Alternatively, should pages using Calcite more generously accept the underline?

cc @hebikidesignworks

**Comment by paulcpederson** [comment]
@jonathantneal an unset mixin is an interesting idea. So this would be something you can call that reverts all the styles?

1. I think you should be explicit with margin and padding on elements. We are unlikely to remove the padding or margin on lists as there are thousands of pages relying on that styling.
2. An unset mixin is an interesting idea, but wondering if it would be more work than it's worth.
2. Yes, after reading WCAG 2.0 guidelines for links I think we should accept the underline on links. Not sure why this didn't get noted in our a11y audit?

So overall, I think the takeaway is to reduce the styles we're adding for raw type elements. But we do want to have these styles remain consistent across browsers. Since I know that is a area of expertise for you, do you happen to know offhand if these different type elements are styled differently in different browsers?

**Comment by paulcpederson** [comment]
Most of the raw html element styles that were problematic have been removed. I am going to close this as I think it's been largely addressed.
