### ISSUE TITLE
Recommendation: Never declare fractional absolute lengths

### ISSUE THREAD

**Issue by jonathantneal** [Esri/calcite-web#826]
I recommend using whole numbers when declaring absolute lengths, like px, em, rem, (cm, etc.). Not all browsers round or alias fractional pixel lengths the same, and there is no spec guidance on the matter. Subpixel sizing is especially problematic for text sizes.

http://www.unumux.com/ux-insights/2016/2/24/subpixel-troubleshooting

Browser APIs inconsistently support returning floated numbers or integers (an unrelated example off the top of my head is `innerWidth`, I believe). I recommend avoiding fractional absolute lengths, especially for `font-size`.

This is, of course, knowing and accepting that fractional lengths naturally occur (as the exception) when using `%`.

Thoughts?

**Comment by paulcpederson** [comment]
I think for pixels we could probably do this. Most likely we'd develop some rounding mixin in Sass, esp for column widths (related: #742). We only really use pixels in a handful of places (mostly the grid), so it wouldn't be that much dev time to go through and iron these out. The grid is sort of difficult, though, because if you round down, columns inside might not fit anymore, so this might actually just cause more bugs, not sure. I think we'd just have to go in and branch and see.

We very infrequently use em, cm, so not a lot to worry about there.

Using whole rem values is completely unworkable as a solution. The jump from 1rem to 2rem is  massive. Is that what you're advocating? No decimals on rem values at all? Maybe I don't understand what we're going for on this front.

Just something to consider, using rems for most padding/spacing allows us to do things like change the base font size for mobile (and all the patterns instantly become slightly more compact). We could reverse-engineer our rems based on whole pixel values, or go through and update all of the patterns padding and spacing at all of the breakpoints, but this is a lot of work. 

> But it may only show up once in a blue moon in the form of some small, very difficult to diagnose, browser-specific bugs

This from the article you linked to made me think a bit. Is it worth rearchitecting the entire framework and rewriting all of the styles, and making lots of breaking changes just to fix rare, hypothetical browser-specific bugs (esp now that we are IE11+)?

**Comment by jonathantneal** [comment]
Ah, I didn’t mean to say 1rem, 2rem, 3rem. I mean computed absolute values, so px.

**Comment by paulcpederson** [comment]
I see, so it would just be a matter of looking at the computed styles and then figuring out which rem values produced even pixels?

**Comment by jonathantneal** [comment]
Also, while the article might talk about older browsers, I think that just makes it easy to dismiss. These issues still exist in Edge and Safari. Subpixel aliasing is not exact science. It’s why I pulled `innerWidth` out of memory. One could also dismiss my arguments because fonts will still look different in different OS’s due to how they handle aliasing in general. I think the philosophy of standing with whole numbers for computed values is about establishing consistency at a reasonable level.

My arguments can totally be dismissed for many reasons, but I would hate to see them dismissed because they also happened to apply to browsers we don’t care about. I just do a horrible job making a case for anything.

**Comment by paulcpederson** [comment]
In next release all media queries, column widths, etc will be even pixel values. Type sizes are now based off 16px so almost all of them are also even pixels now.
