### ISSUE TITLE
Add btn-link class for buttons

### ISSUE THREAD

**Issue by mvdbster** [Esri/calcite-web#846]
Sometimes **buttons** are more suited than `<a href="#">` links (_e.g._, items in dropdown menus). Empty `href` links seem like bad practice, mess with routing, show an ugly status at the bottom of the page when hovering, etc...

It would be good to have a `btn-link` class similar to Bootstrap so that buttons in dropdowns can be styled the same as hyperlinks. Same for headers (`top-nav`) etc...

Alternatively, one could just style `<button class="dropdown-link">` correctly. Same for `<button class="top-nav-link">`.

**Comment by paulcpederson** [comment]
@mvdbster yes I agree. I actually have that exact class in ArcGIS Online already. I'll look at doing two things:

1. port the `btn-link` class over so there is an easy way to style buttons to look like links
2. declare some additional properties on the dropdown and top nav links so they can handle buttons 

In a previous release we removed the styling we had on native button elements, so that should actually make this pretty easy.

**Comment by paulcpederson** [comment]
Added a `btn-link` class, and also make dropdown links and top nav links work with button elements out of the box. Will be part of next release.
