### ISSUE TITLE
Font Weights

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#860]
Issue submitted by Dashboard dev (Fred)

The style for **or is defined as:**

```
 body b, body strong {
    font-weight: 500;
}
```

in faces.scss

This whole font-weight 500 is not working. It doesn't create enough difference for most people:
With strong:
![image](https://user-images.githubusercontent.com/6144462/33278296-f299a24c-d34f-11e7-8faa-6aaa46cdc8ed.png)

Without strong:
![image](https://user-images.githubusercontent.com/6144462/33278306-fa698118-d34f-11e7-88ff-990bc7d752dd.png)

Why is CW not using font-weight: bold?

**Comment by paulcpederson** [comment]
The decision to use `demi-bold` instead of `bold` was made when we did the first designs using Avenir Next. At the time the regular body font was `300`, so `300` to `500` represented sufficient contrast (and a true `700` bold seemed way too much). 

When we changed the body styles a while back, we changed the weight to `400` abd we didn't update the bold weight. I agree it's not enough, now (especially on sub-par monitors). 

As part of this change we should also address the `h1` through `h6` weights as they are still `300`.

**Comment by mjuniper** [comment]
Any eta on getting this addressed? It is affecting Hub too.

**Comment by paulcpederson** [comment]
I probably won't have time to handle this until the new year...

**Comment by paulcpederson** [comment]
FYI this is part of a larger font overhaul we are looking to complete as part of V1 (end of February estimate)

**Comment by paulcpederson** [comment]
The new font implementation fixes this problem. In the next release bold weights should render properly with sufficient contrast.
