### ISSUE TITLE
Some leaky styles when used with ArcGIS API 4 for JavaScript

### ISSUE THREAD

**Issue by odoe** [Esri/calcite-web#866]
I'm working on an app using the ArcGIS API 4 for JavaScript. This is going to be an example app for users.

This impacts some of the dropdowns we have in Search and the Directions widget. It looks like some `li` styles add margins that impact the widgets, and the `h3` makes some of the text really big.

Directions with Calcite
![screen shot 2018-01-04 at 8 28 10 am](https://user-images.githubusercontent.com/206462/34574022-18dfdffe-f12b-11e7-96fd-bad052903c3d.png)

Uncheck the `li` style
![screen shot 2018-01-04 at 8 28 25 am](https://user-images.githubusercontent.com/206462/34574032-20bddafa-f12b-11e7-872d-ba95c2b69826.png)

The Directions widget with no Calcite
![screen shot 2018-01-04 at 8 32 27 am](https://user-images.githubusercontent.com/206462/34574057-2aa16f78-f12b-11e7-9edd-9266f5d4a8e6.png)

I'm using it via the Getting Started guide `"calcite-web": "github:Esri/calcite-web#v1.0.0-rc.8"` and using the no-fonts version.
```
@import "node_modules/calcite-web/dist/sass/calcite-web-no-fonts";
```

Maybe I'm missing something somewhere.

Thanks!

**Comment by paulcpederson** [comment]
@odoe no, you're not missing anything. The `li` styles come straight from the [typographic defaults](http://esri.github.io/calcite-web/documentation/type/#defaults). This is something that has come up before (#852 , #820 , #768) . 

The question at its core is how much does Calcite Web style by default, and how much only happens if you add a class? Previously we provided basic typographic styles for all common html elements (`p`, `h1`-`h6`, `ul`, `li`, `button`, `blockquote`, etc) because that's what consumers of the framework wanted. 

I think we can change the framework to style lists only under a particular class (though this will be a breaking change). So marking this as a bug and assigning to the next release.

---

However, the directions widget should probably set a font size on this h3 element (probably with either the `.esri-widget h3` or `esri-.directions__message` classes). Depending on an `h3` having the default browser font size in a widget that's meant to be used on all kinds of different pages (with different styles) seems like asking for trouble. 

For example, here is the same widget with Bootstrap (the most common CSS framework out there):

<img width="576" alt="screen shot 2018-01-04 at 9 07 15 am" src="https://user-images.githubusercontent.com/1031758/34575355-4bee6984-f12f-11e7-8b67-82f4aca9128a.png">

So my preference is to not remove the h1-h6 styling unless we get a lot more demand for that change. Maybe this could be a Sass variable?

**Comment by asangma** [comment]
> However, the directions widget should probably set a font size on this h3 element (probably with either the .esri-widget h3 or esri-directions__message classes). 

Cool.  I think we could define font-size for the Hs.
@driskull @jcfranco Do you think this should just be done on widgets that are `esri-component`s, i.e. that are on map?  Or across the board, i.e. an H inside `esri-widget`?

**Comment by driskull** [comment]
Seems to me like it should be done on a per widget bases. If a widget defines an H3, it should set it's height. I'm assuming that widgets will not all have the same h3 size.

**Comment by patrickarlt** [comment]
@odoe @paulcpederson we have been maintaining a compatibility stylesheet on the developers site that should cover some of this stuff. Maybe that should be added to Calcite Web for use with the JS API?

**Comment by paulcpederson** [comment]
List styles will be much less intrusive in the next release. Anything past this will need to be handled by the JSAPI styles, but any fixes should be very lightweight now.
