### ISSUE TITLE
Likert Scale Component

### ISSUE THREAD

**Issue by jmdye** [Esri/calcite-web#902]
Any chance we might be able to get a likert scale component down the road? I would find it useful in forms that are more survey-centric. If there are plans to add 'stops' to the range-slider down the road, that might also suffice if I could label each of the stops.

**Comment by macandcheese** [comment]
Hi @jmdye - We just added the base range slider component - and are planning some helpers for it in in https://github.com/Esri/calcite-web/issues/876 down the line. Fixed point labels are a larger task, I'm not sure how heavy we want to make CW in this case vs. deferring to libraries more suited like https://refreshless.com/nouislider/pips/.

**Comment by jmdye** [comment]
Fair enough. What about something like a modifier for in-line radio buttons with a little styling flair to make it feel like a likert scale?

**Comment by macandcheese** [comment]
I'd still recommend using the above library or something similar, rather than try to wrangle the radios into something really custom. Feel free to take the base CW styles and build upon those for something bespoke. Going to close for now, maybe we can take another look at this when we add re-visit more "applike" components down the line.
