### ISSUE TITLE
Deprecate components that exist elsewhere

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-web#918]
- Defer icon docs to https://github.com/ArcGIS/calcite-ui-icons
- Defer top navigation markup and docs to https://github.com/Esri/global-nav

**Comment by jmdye** [comment]
Does this mean you guys are planning to remove top-navigation as a component from CW and instead defer to Esri's Global Nav? That's going to cause some issues for me since I don't have access to that stuff and use CW to build Doc Sites for our my companies internal Esri stack. Hope I'm misinterpreting.

**Comment by paulcpederson** [comment]
You're not misinterpreting. Most likely the first take at this will involve just setting the default config variables, so you will hopefully be able to set `$include-top-navigation: true` and continue to use it. This would involve using Sass, though.

**Comment by jmdye** [comment]
Thanks for the response. I don't mind learning Sass or changing the style - I get that I'm a free rider on this. I just know that I can't access Esri's global-nav or calcite-ui-icons repos because I'm not part of the Esri Org. So if the CW install doesn't include all of the necessary stuff without requiring me to be part of the Esri org, I'll be hosed and forced to remain on an older version of CW that gives me a top-nav.

**Comment by paulcpederson** [comment]
Yeah, you could also just vendor the additional patterns that are being deprecated into your app and use that "patch" over the top of new releases. Just copy and paste what you need and then use the latest, if that makes sense.

**Comment by jmdye** [comment]
That's reasonable - though if at all possible I'd prefer not to. I get that Esri can't share everything and that global-nav is pretty baller. I can certainly see why it wouldn't be made available to anyone outside the org.

**Comment by macandcheese** [comment]
Closing this - will take place through other tasks.
