### ISSUE TITLE
Styles in download do not match examples on site

### ISSUE THREAD

**Issue by elake2018** [Esri/calcite-web#963]
I like the style of calcite and I am developing some ESRI map apps and want to use the JS API 4.7 and Bootstrap 4+. Now I was hoping to find some stripped down sample pages that I could take and get running with (similar to what getbootstrap offers), but it appears I will have to strip out what I don't want. Now I downloaded the latest release from the top link in the nav, I also wanted to start by replicating the nav I have in my existing bootstrap app, but when I use your navigation page as a starting point and look in the dist folder of the download , none of the style sheets file names match. like all.css, extension.css or dark.css, etc.

Am I missing something here?

**Comment by paulcpederson** [comment]
@elake2018 yes. We use Sass to build the css for our documentation, so the names won't match because calcite-web is _included in_ `all.css`. If you don't want to use Sass, and you would like a stripped down file, you could always follow [the quickstart guide](http://esri.github.io/calcite-web/guides/quickstart/). If a guide isn't really your style, you could start with the [get started](http://esri.github.io/calcite-web/documentation/) in the documentation.

We also have some [navigation examples](http://esri.github.io/calcite-web/examples/navigation/), which you could copy and paste into your page and customize. 

A note: I'm not sure how Calcite Web will work with Bootstrap, it's not really meant to be used with other CSS frameworks, so their might be some naming collisions.

**Comment by elake2018** [comment]
I will say I ended up here from calcite-maps. On that project they say what's below to get started which is a little confusing. They appear to be the same project more or less and since both are ESRI I expected maps to an integral part of this calcite-web project, but it's not even mentioned.

"To get started, typically you: 1) Build a Bootstrap HTML page, 2) Add references to Bootstrap and Calcite Maps, and 3) Apply Calcite Maps classes to the elements to style the app with the layout and colors desired."

Thanks for your help.

**Comment by paulcpederson** [comment]
@elake2018 I see, yeah this is a very different project than Calcite Maps. Calcite Maps is a _theme for bootstrap_. This is a totally independent CSS Framework. 

The JSAPI includes widgets for most components you'd want from a mapping perspective, and we [have](https://github.com/Esri/calcite-web/issues/133) [fixed](https://github.com/Esri/calcite-web/issues/580) [several](https://github.com/Esri/calcite-web/issues/663) [issues](https://github.com/Esri/calcite-web/issues/866) to make sure that CW and the JSAPI are compatible. 

CW is not focused on maps at all, but rather on UI and UX related to SaaS applications and marketing pages. Hope that helps?
